export const calle = [
    "A. De Av. Del Café",
    "A. Privada Av Del Café 1",
    "Adolfo Ruiz Cortines",
    "Aguascalientes",
    "Alfaro",
    "Allende",
    "Americas",
    "Andador",
    "Andador 1",
    "Andador Juárez",
    "Andador Serdán",
    "Animas",
    "Antonio Chedraui Caram",
    "Araucarias",
    "Av. Lázaro Cárdenas",
    "Avenida",
    "Avenida Atenas Veracruzana",
    "Avenida Ávila Camacho",
    "Avenida De La República",
    "Avenida De Las Amricas",
    "Avenida De Las Rocallosas",
    "Avenida Del Café",
    "Avenida Enrique C. Rebsamen",
    "Avenida Francisco I Madero",
    "Avenida Jacaranda",
    "Avenida Justino Sarmiento",
    "Avenida Lázaro Cárdenas",
    "Avenida Lomas Del Tejar",
    "Avenida México",
    "Avenida Miguel Alemán",
    "Ávenida Orizaba",
    "Avenida R. Murillo Vidal",
    "Avenida Revolución",
    "Avenida Valles De Cristal",
    "Avenida Venustiano Carranza",
    "Avila Camacho",
    "Belisario Domínguez",
    "Benito Juárez",
    "Betancourt",
    "Boulevard Adolfo Ruiz Cortines",
    "Boulevard Cristobal Colon 5",
    "Manlio Fabio Altamirano",
    "C. Principal",
    "Calle",
    "Calle Adalberto Arroniz Rodriguez",
    "Calle Benito Juárez",
    "Calle Constituyentes De",
    "Calle Coyoacán",
    "Calle De Bremont",
    "Calle Delfino Valenzuela",
    "Calle Enrique Hernández Castillo",
    "Calle Enrique Z. Mercado",
    "Calle Ferrocarril Interoceánico",
    "Calle Francisco Sarabia",
    "Calle Francisco Vázquez",
    "Calle Isauro Sánchez",
    "Calle Joaquín Arroniz",
    "Calle Joaquín Ramírez Cabañas",
    "Calle Magnolia",
    "Calle Manuel Altamirano",
    "Calle Melchor Ocampo",
    "Calle Miguel Hidalgo",
    "Calle Nicolás Bravo",
    "Calle Norberto Martínez",
    "Calle Nuevo León",
    "Calle Oriente 1",
    "Calle Paseo De Xalapa",
    "Calle Pico De Orizaba",
    "Calle Poniente 2",
    "Calle Prolongació Ébano",
    "Calle Rafael Ramírez",
    "Calle San Roque",
    "Calle Santiago Bonilla",
    "Calle Veracruz",
    "Calle Vicente Guerrero",
    "Calle Villahermosa",
    "Calle Volcán De Colima",
    "Calle Zempoala",
    "Callejón De Jesus Te Ampare",
    "Camino Antiguo A Coatepec",
    "Carlos A. Carrillo",
    "Carretera Xalapa Veracruz",
    "Centro De Acondicionamiento Físico Integral.",
    "Chilpancingo",
    "Circuito Palmeras",
    "Circuito Teodoro A. Dehesa",
    "Ciudad Victoria",
    "Clavijero",
    "Coatepec",
    "Colegio Militar",
    "Cristal",
    "De Noviembre",
    "De Pipila",
    "Delfino Valenzuela",
    "Diego Leño",
    "División Del Norte",
    "Doctor Lucio",
    "Doctor Rafael Lucio",
    "Enrique C Rébsamen",
    "Enrique Z. Mercado",
    "Fco. Navarrete",
    "Federico Froebel",
    "Félix Z. Licona",
    "Ferrocarril Interoceanico",
    "Fidencio Ocaña",
    "Francisco I. Madero",
    "Francisco Javier Clavijero",
    "Francisco Lagos Cházaro",
    "Francisco Moreno",
    "Gob. Herrera Tejeda",
    "Gobierno Del Estado De Veracruz Oficina Hacienda",
    "Guadalupe Victoria",
    "Gustavo Díaz Ordaz",
    "Gutiérrez Zamora",
    "Honduras 5",
    "Human De Xalapa",
    "Iglesia Catolica El Buen Pastor",
    "Ignacio De La Llave",
    "Independencia",
    "Insurgentes",
    "J. Azueta",
    "Jalisco",
    "Jesús Reyes Heroles",
    "Jorge Serdan",
    "Jorullo",
    "José Azueta",
    "José De Jesús Núñez Y Domínguez",
    "Juan De La Luz Enríquez",
    "Juan Escutia 2",
    "Juárez",
    "Justino Sarmiento",
    "Landero Y Coss",
    "Lázaro Cárdenas",
    "Libertad",
    "Lucio Blanco",
    "Luis Hidalgo Monroy",
    "Maestros Veracruzanos",
    "Magnolia",
    "Manuel Ávila Camacho",
    "Manuel C. Tello",
    "Mártires",
    "Médicos",
    "Melchor Ocampo",
    "Mérida",
    "México",
    "Miguel Alemán",
    "Miguel Hidalgo",
    "Morelos",
    "Municipal",
    "Municipio De Xalapa",
    "Municipio De Xalapa Catastro",
    "Niños Heroes",
    "Nuevo Leon",
    "Obrero Mundial",
    "Orizaba",
    "Pablo Galeana",
    "Pasaje Tanos",
    "Paseo De Las Araucarias",
    "Paseo De Las Araucarias 7",
    "Paseo De Los Maestros",
    "Paseo De Xalapa",
    "Paseo Xalapa",
    "Pipila",
    "Plazuela Fco. J. Clavijero",
    "Poeta Angel Núñez Beltrán",
    "Primo Verdad",
    "Privada Del Café",
    "Prolongación",
    "Prolongación Guadalajara",
    "Prolongación Pipila",
    "Rafael Murillo Vidal",
    "Rébsamen",
    "Revolución",
    "Río Jamapa",
    "Rio Nautla",
    "Ruiz Cortines",
    "S",
    "Santos Degollado",
    "Sayago",
    "Sebastián Camacho",
    "Servicios Integrados De Xalapa",
    "Simon Bolívar",
    "Tapachula",
    "Teotihuacan",
    "Tepic",
    "Toluca",
    "Torre Hakim",
    "Ursulo Galván",
    "Venustiano Carranza",
    "Veracruz",
    "Violeta",
    "Xalapa",
    "Xalapeños Ilustres",
    "Zempoala"
];