export const colonia = [
    "10 De Abril",
    "10 De Mayo",
    "12 De Diciembre",
    "13 De Septiembre",
    "14 De Febrero",
    "16 De Septiembre",
    "18 De Marzo",
    "2 De Abril",
    "2 De Julio",
    "2 Vistas",
    "21 De Marzo",
    "23 De Marzo",
    "24 De Abril",
    "26 De Agosto",
    "3 De Mayo",
    "6 De Septiembre",
    "7 De Noviembre",
    "Acueducto",
    "Acueducto Animas",
    "Adalberto Tejeda",
    "Adolfo Lopez Mateos",
    "Agricola",
    "Agricola",
    "Agua Clara",
    "Agua Santa",
    "Agua Santa Ii",
    "Aguacatal",
    "Altamira",
    "Alvaro Obregon",
    "Amozorrutia",
    "Ampl 21 De Marzo",
    "Ampl Brisas",
    "Ampl Framboyanes",
    "Ampl Higueras",
    "Ampl Libertad",
    "Ampl Lomas De Casa Blanca",
    "Ampl Margarita Maza De Juarez",
    "Ampl Predio La Virgen",
    "Ampl Rafael Murillo Vidal",
    "Ampl Renacimiento",
    "Ampl Union",
    "Ampl Union Sumidero",
    "Ampl. Vasconcelos",
    "Anahuac",
    "Andres Montes",
    "Arboledas De Agua Santa",
    "Arboledas Del Sumidero",
    "Arboledas Del Tronconal",
    "Arroyo Blanco",
    "Arroyo Zarco",
    "Atenas De Casa Blanca",
    "Aviacion Civil",
    "Azteca",
    "Badillo",
    "Balcones De Jalapa",
    "Barrio El Calvario",
    "Barrio La Palma",
    "Barrio La Tranca",
    "Barrio Loma Bonita",
    "Barrio Lomas De Los Castillos",
    "Belisario Dominguez",
    "Bellavista",
    "Benito Juarez",
    "Benito Juarez Sur",
    "Bosques De Las Lomas",
    "Brisas Del Rio Sedeño",
    "Buenavista",
    "Buenavista Ii",
    "Bugambilias Del Sumidero",
    "Burocrata Federal",
    "Burocratas Del Ayuntamiento",
    "Caminos",
    "Campestre",
    "Campo De Tiro",
    "Campo Nuevo",
    "Cañada Las Animas",
    "Carolino Anaya",
    "Casa Blanca",
    "Castillo De Las Animas",
    "Central De Abastos",
    "Cerro Colorado",
    "Cfe Suterm",
    "Cincuentenario Casa Blanca",
    "Cipe",
    "Coapexpan",
    "Colonias De Jalapa",
    "Comercio",
    "Comision Federal De Electricidad",
    "Comunicaciones",
    "Constitucion Del Sumidero",
    "Constituyentes",
    "Continental",
    "Cuauhtemoc",
    "Culturas Mexicanas",
    "Dante Delgado Ranauro",
    "Del Bosque",
    "Del Maestro",
    "Del Moral",
    "Del Valle",
    "Desarrollo Social San Bruno",
    "Diamante",
    "Divisadero",
    "Dolores Hidalgo",
    "Ejido Del Tronconal",
    "El Cafetal",
    "El Coyol",
    "El Empleado",
    "El Haya",
    "El Maestro",
    "El Mirador",
    "El Naranjal De Agua Santa",
    "El Olmo",
    "El Pocito",
    "El Policia",
    "El Porvenir",
    "El Porvenir Ii",
    "El Sumidero",
    "El Tanque",
    "Electricistas",
    "Empleados Hacendarios",
    "Encantos Del Sumidero",
    "Encinal",
    "Ensueño",
    "Estibadores",
    "Eucalipto",
    "Federal",
    "Felipe Carrillo Puerto",
    "Ferrer Guardia",
    "Ferrocarrilera",
    "Ferrocarriles",
    "Flores De Casa Blanca",
    "Floresta",
    "Formosa",
    "Fracc Barranca Honda",
    "Fracc Chulavista",
    "Fracc Colibris",
    "Fracc El Arroyo",
    "Fracc El Cafetal",
    "Fracc El Tucan",
    "Fracc Felipe Romero",
    "Fracc Jardines De Las Flores 2000",
    "Fracc La Loma",
    "Fracc Las Jacarandas",
    "Fracc Loma Alta",
    "Fracc Lomas Las Margaritas",
    "Fracc Lucas Martin",
    "Fracc Miradores De Santa Rosa",
    "Fracc Presa De San Bruno",
    "Fracc Rubi Animas",
    "Fracc Vista Hermosa",
    "Fracc Zippor",
    "Framboyanes",
    "Francisco I Madero",
    "Francisco Sarabia",
    "Francisco Villa",
    "Fuentes De Las Animas",
    "Guadalupe Rodriguez",
    "Guadalupe Victoria",
    "Guayabal",
    "Gutierrez Barrios",
    "Heriberto Castillo Martinez",
    "Heroes Ferrocarrileros",
    "Heron Proal",
    "Higueras",
    "Hogares Ferrocarrileros",
    "Huizachal",
    "Ignacio De La Llave",
    "Indeco Animas",
    "Independencia",
    "Independencia Sur",
    "Industrial",
    "Industrial Linda Vista",
    "Infonavit Loma Alta",
    "Infonavit Pomona",
    "Ing Rivadeneyra",
    "Inmecafe",
    "Internacional",
    "Invervi",
    "Isauro Acosta",
    "Isleta",
    "Jacarandas",
    "Jalapa 2000",
    "Jalapeños Ilustres",
    "Jardines De Agustin Lara",
    "Jardines De Bambu",
    "Jardines De Jalapa",
    "Jardines De La Pradera",
    "Jardines De Las Animas",
    "Jardines De Santa Rosa",
    "Jardines De Santa Rosa 2Da Secc",
    "Jardines Del Castillo",
    "Jongitud Barrios",
    "Jose Cardel",
    "Jose De Jesus Panes",
    "Jose Vasconcelos",
    "Josefa Ortiz De Dominguez",
    "Juan De La Luz Enriquez Sur",
    "La Herradura",
    "La Lagunilla",
    "La Morera",
    "La Pedreguera",
    "La Piedad",
    "La Union",
    "Laderas Del Macuiltepetl",
    "Las Aguilas",
    "Las Arboledas",
    "Las Brisas",
    "Las Flores",
    "Las Margaritas",
    "Las Minas",
    "Las Torres",
    "Lazaro Cardenas",
    "Lealtad Institucional",
    "Libertad",
    "Lomas De Casa Blanca",
    "Lomas De Casa Blanca Sect Higueras",
    "Lomas De Chapultepec",
    "Lomas De La Candelaria",
    "Lomas De Las Americas",
    "Lomas De Oro",
    "Lomas De San Roque",
    "Lomas De Tecuanapan",
    "Lomas De Vista Hermosa",
    "Lomas Del Estadio",
    "Lomas Del Paraiso",
    "Lomas Del Sedeño",
    "Lomas Del Seminario",
    "Lomas Del Sumidero",
    "Lomas Del Tejar",
    "Lomas Verdes Secc 2",
    "Lomas Verdes Secc 3",
    "Lomas Verdes Secc 4",
    "Los Angeles",
    "Los Cedros",
    "Los Encinos",
    "Los Laureles",
    "Los Pinos",
    "Los Prados",
    "Los Reyes",
    "Los Sauces",
    "Luis Donaldo Colosio",
    "Luz Del Barrio",
    "Macuiltepetl",
    "Manantiales",
    "Manantiales",
    "Marco Antonio Muñiz",
    "Marco Antonio Muñoz",
    "Margarita Maza De Juarez",
    "Maria Esther",
    "Maver",
    "Mesa Del Guayabo",
    "Mexico",
    "Miguel Aleman",
    "Miguel Hidalgo",
    "Mirador Iii",
    "Miradores De Las Flores",
    "Miradores De San Roque",
    "Miradores Del Sumidero",
    "Mision San Carlos",
    "Moctezuma",
    "Modelo",
    "Montevideo",
    "Morelos",
    "Nacimiento",
    "Nacional",
    "Nahuiolli",
    "Niños Heroes",
    "Nuevo Jalapa",
    "Nuevo Sol",
    "Obrero Campesina",
    "Obrero Mundial",
    "Obreros Textiles",
    "Olmos De Las Animas",
    "Panorama",
    "Paseo De Los Lagos",
    "Pastoresa",
    "Pedregal De Las Animas",
    "Pedregal El Sumidero",
    "Peñascal",
    "Periodistas",
    "Plan De Ayala",
    "Plaza Las Américas",
    "Pomarosas",
    "Popular De Las Animas",
    "Porton Colorado",
    "Porvenir",
    "Predio La Virgen",
    "Predio Palo Blanco",
    "Progreso",
    "Progreso Macuiltepetl Norte",
    "Progreso Macuiltepetl Sur",
    "Provipo",
    "Pumar Choferes",
    "Rafael Hernandez Ochoa I",
    "Rafael Hernandez Ochoa Ii",
    "Rafael Hernandez Ochoa Iii",
    "Rafael Hernandez Villapaldo",
    "Rafael Lucio",
    "Rafael Murillo Vidal",
    "Rafael Murillo Vidal Norte",
    "Rafael Murillo Vidal Sur",
    "Real Del Bosque",
    "Rebombeo De Las Animas",
    "Reforma",
    "Renacimiento",
    "Represa Del Carmen",
    "Res Mirador",
    "Res Presa De San Bruno",
    "Reserva Territorial",
    "Residencial Los Angeles",
    "Revolucion",
    "Rotaria",
    "Ruben Pabellon Acosta",
    "Ruben R Jaramillo",
    "Sacrificio",
    "Sahop",
    "Salud",
    "Salvador Diaz Miron",
    "Santa Anita",
    "Santa Barbara",
    "Santa Rosa",
    "Sebastian Lerdo De Tejada Indeco",
    "Servidor Agrario",
    "Sipeh Animas",
    "Solidaridad",
    "Sostenes Mejia Blanco",
    "Tabasco",
    "Tamborrel",
    "Tatahuicapan",
    "Teresa Peñafiel",
    "Tulipanes",
    "Tulipanes De La Animas",
    "Ucis Ver",
    "Udic",
    "Une Pri",
    "Unidad Bosque Pensiones",
    "Unidad Del Bosque Ferrocarrilero",
    "Unidad Deportiva El Castillo",
    "Unidad Hab Arboledas De Jalapa",
    "Unidad Hab Buenavista I",
    "Unidad Hab Empleados Municipales",
    "Unidad Hab Fovissste",
    "Unidad Hab La Haya",
    "Unidad Hab Los Lagos",
    "Unidad Hab Marco Antonio Muñoz",
    "Unidad Hab Nuevo Jalapa",
    "Unidad Hab Sumidero Infonavit",
    "Unidad Hab Union Ferrocarrilera",
    "Unidad Jardin Pensiones",
    "Unidad Magisterial",
    "Unidad Progreso",
    "Unidad Veracruzana",
    "Unidad Y Trabajo",
    "Valle Anahuac",
    "Valle De Cristal",
    "Valle De Los Pinos",
    "Valle Del Sol",
    "Vanguardia Revolucionaria",
    "Venustiano Carranza",
    "Veracruz",
    "Veracruz Sur",
    "Vicente Guerrero",
    "Villarreal",
    "Virginia Cordero Murillo",
    "Voceador",
    "Xaltic",
    "Zapote",
    "Zona Centro",
    "Zona Militar",
    "Zona Universitaria"
];